#!/bin/bash
# scripts/merge.sh
set -e

echo "Starting document compilation..."

# Clean old outputs if any
rm -f full_document.md

# Collect all markdown files in the root folder, excluding README.md and full_document.md
shopt -s nullglob
files=()
for f in *.md; do
  if [[ "$f" != "README.md" && "$f" != "full_document.md" ]]; then
    files+=("$f")
  fi
done

# Sort alphabetically
IFS=$'\n' sorted_files=($(sort <<<"${files[*]}"))
unset IFS

if [ ${#sorted_files[@]} -eq 0 ]; then
  echo "Error: No markdown files found to merge."
  exit 1
fi

# Concatenate all sorted markdown files into full_document.md
for file in "${sorted_files[@]}"; do
  echo "Merging: $file"
  cat "$file" >> full_document.md
  # Append newlines to guarantee clean transitions
  echo -e "\n\n" >> full_document.md
done

echo "Adding autogenerated git changelog page..."
# Add a page break and the changelog section header
echo -e "\n\n<div class=\"page\"></div>\n\n# Registro de Cambios (Autogenerado)\n" >> full_document.md
echo -e "Este reporte fue generado automáticamente. A continuación se detallan los últimos cambios registrados en el repositorio:\n" >> full_document.md
echo -e "## Información de Compilación\n" >> full_document.md
echo -e "- **Fecha:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')\n" >> full_document.md
echo -e "- **Commit:** \`$(git rev-parse --short HEAD 2>/dev/null || echo "N/A")\`\n" >> full_document.md
echo -e "- **Rama:** \`$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "N/A")\`\n" >> full_document.md

echo -e "## Últimos Commits\n" >> full_document.md
git log -n 5 --pretty=format:"- **%h** - *%an* (%ad): %s" --date=short >> full_document.md 2>/dev/null || echo "No git history found" >> full_document.md
echo -e "\n\n" >> full_document.md

echo -e "## Archivos Modificados en el Último Commit\n" >> full_document.md
git diff-tree --no-commit-id --name-only -r HEAD >> full_document.md 2>/dev/null || echo "No modified files found" >> full_document.md
echo -e "\n" >> full_document.md

echo "Successfully merged files and added changelog to full_document.md"
